package com.yunhwan.auth.error.domain.consumer;

public enum DeadLetterReasonCode {
    CONTRACT_MISSING_OUTBOX_ID,
    CONTRACT_MISSING_EVENT_TYPE,
    CONTRACT_MISSING_AGGREGATE_TYPE,
    CONTRACT_MISSING_HEADERS,
    PAYLOAD_INVALID_JSON,
    PAYLOAD_MISSING_AUTH_ERROR_ID,
    DOMAIN_AUTH_ERROR_NOT_FOUND,
    HANDLER_NON_RETRYABLE,
    RETRY_EXHAUSTED,
    CONSUMER_PROCESSING_FAILED,
    BROKER_REJECTED,
    BROKER_EXPIRED,
    BROKER_MAXLEN,
    UNKNOWN
}
